@startuml
    left to right direction

    usecase "Evaluar solicitud\n de crédito" as uc1
    usecase "Solicitar información\n adicional al cliente" as uc2

    :Agente: as agn

    agn --> uc1
    uc1 <|-- uc2 : <<extend>>
@enduml